### ISSUE TITLE
Golang list modules command timesout after 30 minutes

### ISSUE THREAD

**Issue by Anshu2405** [dependency-check/DependencyCheck#2894]
**Describe the bug**
Golang list modules command timesout after 30 minutes
Please note that same command works outside the dependencycheck (with the same environment where the dependency checker is run).
When executed outside dependency checker, "go  list -m all" lists 541 dependencies and "go  list -json -m all" gives 4551 lines of output.
**Version of dependency-check used**
6.0.2
**Log file**
2020-10-14 12:42:32,271 org.owasp.dependencycheck.analyzer.GolangModAnalyzer:242
INFO  - Golang Mod Analyzer is enabled.
2020-10-14 12:42:32,271 org.owasp.dependencycheck.Engine:762
DEBUG - Starting Golang Mod Analyzer
2020-10-14 12:42:32,271 org.owasp.dependencycheck.Engine:810
DEBUG - Parallel processing with up to 16 threads: Golang Mod Analyzer.
2020-10-14 12:42:32,272 org.owasp.dependencycheck.AnalysisTask:86
DEBUG - Begin Analysis of '<path>/go.mod' (Golang Mod Analyzer)
2020-10-14 12:42:32,272 org.owasp.dependencycheck.analyzer.GolangModAnalyzer:197
INFO  - Launching: [go, list, -json, -m, all] from <path>
2020-10-14 13:12:32,272 org.owasp.dependencycheck.Engine:1128
ERROR - Analysis task was cancelled.
2020-10-14 13:12:32,272 org.owasp.dependencycheck.AnalysisTask:90
WARN  - An error occurred while analyzing '<path>/go.mod' (Golang Mod Analyzer).
2020-10-14 13:12:32,275 org.owasp.dependencycheck.AnalysisTask:91
DEBUG -
org.owasp.dependencycheck.analyzer.exception.AnalysisException: go process interrupted
        at org.owasp.dependencycheck.analyzer.GolangModAnalyzer.analyzeDependency(GolangModAnalyzer.java:293)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
        at org.owasp.dependencycheck.analyzer.GolangModAnalyzer.analyzeDependency(GolangModAnalyzer.java:290)
        ... 7 common frames omitted
2020-10-14 13:12:32,275 org.owasp.dependencycheck.Engine:1129
DEBUG -
java.util.concurrent.CancellationException: null
        at java.util.concurrent.FutureTask.report(FutureTask.java:121)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.owasp.dependencycheck.Engine.executeAnalysisTasks(Engine.java:773)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:673)
        at org.owasp.dependencycheck.App.runScan(App.java:270)
        at org.owasp.dependencycheck.App.run(App.java:202)
        at org.owasp.dependencycheck.App.main(App.java:83)
2020-10-14 13:12:32,585 org.owasp.dependencycheck.App:218
ERROR - One or more fatal errors occurred
2020-10-14 13:12:32,586 org.owasp.dependencycheck.App:224
ERROR - go process interrupted
2020-10-14 13:12:32,586 org.owasp.dependencycheck.App:225
DEBUG - unexpected error
org.owasp.dependencycheck.analyzer.exception.AnalysisException: go process interrupted
        at org.owasp.dependencycheck.analyzer.GolangModAnalyzer.analyzeDependency(GolangModAnalyzer.java:293)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
        at org.owasp.dependencycheck.analyzer.GolangModAnalyzer.analyzeDependency(GolangModAnalyzer.java:290)
        ... 7 common frames omitted
2020-10-14 13:12:32,586 org.owasp.dependencycheck.utils.Settings:751
DEBUG - Deleting ALL temporary files from `<path>/<file>`
2020-10-14 13:12:32,620 org.owasp.dependencycheck.App:84
DEBUG - Exit code: -13

**Expected behavior**
Report should be clean without any errors.

**Comment by jeremylong** [comment]
Please provide:
- the version of go being used:
- OS used:
- A copy of the `go.mod` and `go.sum`:

**Comment by Anshu2405** [comment]
Tried the same test case using Dependency checker version 6.0.3 and seeing same behavior.

Below is the exception

DEBUG - Begin Analysis of '<path>/go.mod' (Golang Mod Analyzer)
2020-11-11 06:59:55,475 org.owasp.dependencycheck.analyzer.GolangModAnalyzer:131
WARN  - Path to `go` executable not set. Trying default location. If you do want to set it, please set the `analyzer.golang.path` property
2020-11-11 06:59:55,475 org.owasp.dependencycheck.analyzer.GolangModAnalyzer:197
INFO  - Launching: [go, list, -json, -m, all] from <path>
2020-11-11 07:29:55,475 org.owasp.dependencycheck.Engine:1128
ERROR - Analysis task was cancelled.
2020-11-11 07:29:55,475 org.owasp.dependencycheck.AnalysisTask:90
WARN  - An error occurred while analyzing '<path>/go.mod' (Golang Mod Analyzer).
2020-11-11 07:29:55,477 org.owasp.dependencycheck.Engine:1129
DEBUG -
java.util.concurrent.CancellationException: null
        at java.util.concurrent.FutureTask.report(FutureTask.java:121)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.owasp.dependencycheck.Engine.executeAnalysisTasks(Engine.java:773)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:673)
        at org.owasp.dependencycheck.App.runScan(App.java:271)
        at org.owasp.dependencycheck.App.run(App.java:203)
        at org.owasp.dependencycheck.App.main(App.java:84)
2020-11-11 07:29:55,477 org.owasp.dependencycheck.AnalysisTask:91
DEBUG -
org.owasp.dependencycheck.analyzer.exception.AnalysisException: go process interrupted
        at org.owasp.dependencycheck.analyzer.GolangModAnalyzer.evaluateProcess(GolangModAnalyzer.java:331)
        at org.owasp.dependencycheck.analyzer.GolangModAnalyzer.analyzeDependency(GolangModAnalyzer.java:318)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
        at org.owasp.dependencycheck.analyzer.GolangModAnalyzer.evaluateProcess(GolangModAnalyzer.java:328)
        ... 8 common frames omitted


Below are the environment details

Go version : go version go1.14.4 linux/amd64.
OS Version : Red Hat Enterprise Linux Server release 7.7 (Maipo)
A copy of the go.mod and go.sum: Attached.

[gomod.txt](https://github.com/jeremylong/DependencyCheck/files/5529944/gomod.txt)
[gosum.txt](https://github.com/jeremylong/DependencyCheck/files/5529946/gosum.txt)


Below are the additional observations/information

1) As per the thread dump, dependency checker is seen waiting at GolangModAnalyzer.evaluateProcess and then gets interrupted after 30 mins.
2) The dependency check analysis is working with dependency checker version 5.3.2 with the same go.mod.
3) Executed the command  go list -json -m all on command line and no hang seen

**Comment by fpytloun** [comment]
Hello, I am seeing same issue with kubernetes project: https://github.com/kubernetes/kubernetes

**Comment by jeremylong** [comment]
I believe this is fixed in the latest. Can anyone confirm?

**Comment by benjsmi** [comment]
Can confirm that I'm still seeing a very similar issue in 6.2.2.

**Comment by andrewmarklloyd** [comment]
Also confirming the same issue in 6.2.2. Any estimate on a fix for this?

**Comment by chadlwilson** [comment]
Believe this is stale/outdated so closing. Can reopen if still relevant.
