### ISSUE TITLE
ConcurrentModificationException followed by a NullpointerException during dependency check analysis

### ISSUE THREAD

**Issue by imotsch** [dependency-check/DependencyCheck#4120]
**Describe the bug**
When running owasp-dependency-check as part of a jenking build, randomly this exception occurs and braks the build.

**Version of dependency-check used**
The problem occurs using version 6.5.3 and also 7.0.0 of the maven plugin
dependency-check-maven:6.5.3:aggregate
dependency-check-maven:7.0.0:aggregate

**Log file**
https://gist.github.com/imotsch/8d26f53c9eab048625f751b18d2e7345

**To Reproduce**
The nature of a CME is typically a non guarded parallel (or java util stream parallel) code section. Therefore we cannot reproduce it every time. It fails approx. in 3 of 5 runs.
We run dependency-check-maven:6.5.3:aggregate on a git repo containing a java rest application built with maven together with a npm javascript ui built with a package.json.

**Expected behavior**
Expected to not fail with this kind of error. A parallel code sections in owasp-dependency-check maybe lacks a guard or is using parallelStream() with code that is not prepared for it.

**Comment by jeremylong** [comment]
This should be fixed in the 7.0.0 release. Can you please validate?

**Comment by imotsch** [comment]
Tested with 7.0.0. Still failed 3 of 5 times, when I run the exact same job 5 times.
The exception is not anymore the NullPointerException or the ConcurrentModificationException but now it is:

[2022-03-01T18:08:56.546Z] [ERROR] Failed to execute goal org.owasp:dependency-check-maven:7.0.0:aggregate (default-cli) on project com.[redacted].parent: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[2022-03-01T18:08:56.546Z] [ERROR] 	AnalysisException: Failed to request component-reports
[2022-03-01T18:08:56.546Z] [ERROR] 		caused by TransportException: Unexpected response; status: 504

[2022-03-10T00:08:18.753Z] Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
[2022-03-10T00:08:18.753Z] 	Failed to request component-reports
[2022-03-10T00:08:18.753Z]     at org.owasp.dependencycheck.Engine.analyzeDependencies (Engine.java:722)
[2022-03-10T00:08:18.753Z]     at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck (BaseDependencyCheckMojo.java:1605)
[2022-03-10T00:08:18.753Z]     at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute (BaseDependencyCheckMojo.java:882)
[2022-03-10T00:08:18.753Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2022-03-10T00:08:18.753Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2022-03-10T00:08:18.753Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2022-03-10T00:08:18.753Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2022-03-10T00:08:18.753Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2022-03-10T00:08:18.753Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2022-03-10T00:08:18.753Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2022-03-10T00:08:18.753Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2022-03-10T00:08:18.753Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2022-03-10T00:08:18.753Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-03-10T00:08:18.753Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-03-10T00:08:18.753Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
[2022-03-10T00:08:18.753Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
[2022-03-10T00:08:18.753Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
[2022-03-10T00:08:18.753Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-03-10T00:08:18.753Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-03-10T00:08:18.753Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-03-10T00:08:18.753Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-03-10T00:08:18.753Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-03-10T00:08:18.753Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-03-10T00:08:18.753Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-03-10T00:08:18.753Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

**Comment by imotsch** [comment]
And in other jobs I found that the http error code may differ:
caused by TransportException: Unexpected response; status: 502
caused by TransportException: Unexpected response; status: 504

**Comment by imotsch** [comment]
Also in 7.0.0 still failing. Any progress on this?

mvn
-f
a.b.c.d
-e
-B
-Dstyle.color=always
org.owasp:dependency-check-maven:7.0.0:aggregate
-Dformats=html,xml
-DskipTestScope=true
-DassemblyAnalyzerEnabled=false

An unexpected error occurred during analysis of '/home/jenkins/agent/workspace/.../package.json' (Node.js Package Analyzer): null
10:03:01  [ERROR] 
10:03:01  java.util.ConcurrentModificationException
10:03:01      at java.util.TreeMap$KeySpliterator.forEachRemaining (TreeMap.java:2750)
10:03:01      at java.util.stream.ReferencePipeline$Head.forEach (ReferencePipeline.java:658)
10:03:01      at org.owasp.dependencycheck.analyzer.DependencyMergingAnalyzer.mergeDependencies (DependencyMergingAnalyzer.java:156)
10:03:01      at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies (NodePackageAnalyzer.java:419)
10:03:01      at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.analyzeDependency (NodePackageAnalyzer.java:265)
10:03:01      at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze (AbstractAnalyzer.java:131)
10:03:01      at org.owasp.dependencycheck.AnalysisTask.call (AnalysisTask.java:88)
10:03:01      at org.owasp.dependencycheck.AnalysisTask.call (AnalysisTask.java:37)
10:03:01      at java.util.concurrent.FutureTask.run (FutureTask.java:264)
10:03:01      at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
10:03:01      at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
10:03:01      at java.lang.Thread.run (Thread.java:834)

**Comment by marcelstoer** [comment]
I feel this should be closed as the NPE was fixed and the concurrent modification is tracked in #4374.

**Comment by imotsch** [comment]
Duplicate to https://github.com/jeremylong/DependencyCheck/issues/4374.
