### ISSUE TITLE
PomParseException occurs while parsing pom of Checkstyle 7.8.2

### ISSUE THREAD

**Issue by longjun2013** [dependency-check/DependencyCheck#801]
### Reporting Bugs/Errors
I'm running with Gradle, the detail pom file and error log are under below link,
https://gist.github.com/longjun2013/c377a861072c70a182e5c7431c02c46e

The gradle plugin version is 2.0.1,  org.owasp:dependency-check-gradle:2.0.1 

My build version infos:
-----------------
Gradle 3.5

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Mac OS X 10.12.5 x86_64

**Comment by jeremylong** [comment]
The checkstyle pom contained an invalid XML entity (&amps;). I've updated the code to better handle unknown entities rather then throwing an exception. This patch will be included in the next release.

**Comment by acooper** [comment]
I just tried the latest 2.0.2-SNAPSHOT version of dependency-check-gradle and it is still having an issue with checkstyle. Is this expected? (in other words it hasn't been fixed yet - which is fine, just want to confirm).

**Comment by jeremylong** [comment]
The issue has been resolved. The issue is that the gradle 2.0.2-snapshot was still pointing at the core-2.0.1 dependency (rather then the snapshot version).

2.1.0 was just pushed and should resolve the issue. Please let me know if you run into any other issues.

**Comment by acooper** [comment]
Verified issue resolved with 2.1.0. Thanks for the quick turn around Jeremy!

**Comment by longjun2013** [comment]
Yeah, "org.owasp:dependency-check-gradle:2.1.0" fixed this issue, thanks @jeremylong
